#!/usr/bin/env python2.5

## Dump extended attributes from one directory tree to a python
## expression to the standard output.
import sys, os, os.path, xattr, stat

# Check command line options
if len(sys.argv) != 2:
  print >> sys.stderr, "usage: %s dir", sys.argv[0]
  sys.exit(1)

src = sys.argv[1]

# Dump all extended attributes in the source tree.  For symlinks read
# the attributes on the link itself, not on the file the symlink
# points to.  If attributes cannot be retrieved for a file (such as a
# protected socket) skip the file; assume back-up already did the right
# thing and the attributes aren't interesting enough to fail on.
print "xa = {"
for root, dirs, files in os.walk(src):
  for f in dirs + files:
    sfname = "%s/%s" % (root, f)
    fname = sfname[len(src)+1:]
    try:
      fxa = xattr.listxattr(sfname, True)
      if len(fxa) > 0:
	      print "%s: %s," % \
		(repr(fname), repr(dict((a, xattr.getxattr(sfname, a, True)) for a in fxa)))
    except Exception, e:
      print >> sys.stderr, e
print "}"
